<a href="https://colab.research.google.com/github/doSwayamCode/ml-daily/blob/main/GridSearchCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X = df.drop('species',axis = 1)
y = df['species']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.33, random_state=42)

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
model_knn = KNeighborsClassifier(n_neighbors=13)

In [10]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [11]:
model_knn.score(X_test,y_test)

1.0

In [12]:
from sklearn.svm import SVC

In [13]:
model_svm = SVC(gamma= 'auto')

In [14]:
model_svm.fit(X_train,y_train)

SVC(gamma='auto')

In [15]:
model_svm.score(X_test,y_test)

1.0

#Now let's use Grid search CV

In [16]:
from sklearn.model_selection import GridSearchCV

In [17]:
classifier = GridSearchCV((model_svm),{
    'C' : [1,10,20,30],
    'kernel' :['rbf','linear'],
},cv = 5,return_train_score = False)

In [18]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [19]:
classifier.cv_results_

{'mean_fit_time': array([0.00193977, 0.0022716 , 0.00168576, 0.00162654, 0.00171022,
        0.00158148, 0.00158896, 0.00162868]),
 'std_fit_time': array([5.16215526e-04, 1.12418737e-03, 5.24691207e-05, 5.31204727e-05,
        5.76538127e-05, 1.99733875e-05, 4.95370699e-05, 2.12358153e-04]),
 'mean_score_time': array([0.00126109, 0.00135946, 0.00123124, 0.0012157 , 0.00123858,
        0.00120506, 0.00118489, 0.0012423 ]),
 'std_score_time': array([7.30541293e-05, 2.64534455e-04, 3.41214888e-05, 3.12773918e-05,
        2.91553852e-05, 4.48383142e-05, 2.77531515e-05, 1.00794691e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [20]:
results = pd.DataFrame(classifier.cv_results_)

In [21]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001940,0.000516,0.001261,0.000073,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002272,0.001124,0.001359,0.000265,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.001686,0.000052,0.001231,0.000034,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.001627,0.000053,0.001216,0.000031,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.001710,0.000058,0.001239,0.000029,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.001581,0.000020,0.001205,0.000045,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.001589,0.000050,0.001185,0.000028,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.001629,0.000212,0.001242,0.000101,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [22]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [23]:
from sklearn.model_selection import RandomizedSearchCV

In [24]:
classifier_r = RandomizedSearchCV((model_svm),{
    'C' : [1,10,20,30],
    'kernel' :['rbf','linear'],
},n_iter = 4,cv = 5,return_train_score = False)

In [25]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [26]:
results = pd.DataFrame(classifier_r.cv_results_)

In [27]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002839,0.001304,0.001707,0.000428,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002061,0.000630,0.001356,0.000114,linear,30,"{'kernel': 'linear', 'C': 30}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,4
2,0.001753,0.000078,0.001308,0.000029,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,3
3,0.001724,0.000081,0.001287,0.000057,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1

In [28]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1       30       linear         0.960000
2       20          rbf         0.966667
3       10          rbf         0.980000